Exception occurred on 2025-07-15 00:03:30.184037:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 00:03:30.319274:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 00:03:30.452920:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 00:03:30.662689:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 00:03:30.806083:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 00:03:30.986539:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 00:23:29.959797:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 00:23:30.067931:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 00:23:30.235518:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 00:23:30.481985:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 00:23:30.720067:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 00:23:30.873306:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 00:43:29.916900:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 00:43:30.055939:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 00:43:30.170284:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 00:43:30.318877:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 00:43:30.516568:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 00:43:30.682703:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 01:03:29.958693:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 01:03:30.127576:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 01:03:30.228540:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 01:03:30.356649:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 01:03:30.554607:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 01:03:30.691529:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 01:23:29.918283:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 01:23:30.031487:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 01:23:30.142924:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 01:23:30.300560:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 01:23:30.428661:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 01:23:30.559429:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 01:43:29.975632:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 01:43:30.133746:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 01:43:30.246747:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 01:43:30.374419:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 01:43:30.540936:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 01:43:30.693648:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 02:03:29.955110:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 02:03:30.063764:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 02:03:30.203384:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 02:03:30.351442:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 02:03:30.495620:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 02:03:30.654395:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 02:23:29.967267:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 02:23:30.117411:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 02:23:30.271694:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 02:23:30.441922:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 02:23:30.622303:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 02:23:30.812212:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 02:43:30.007150:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 02:43:30.133206:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 02:43:30.253931:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 02:43:30.440031:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 02:43:30.607552:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 02:43:30.781647:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 03:03:29.968089:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 03:03:30.097753:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 03:03:30.234883:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 03:03:30.428379:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 03:03:30.601423:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 03:03:30.772803:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 03:23:30.002313:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 03:23:30.162102:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 03:23:30.308214:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 03:23:30.493746:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 03:23:30.638560:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 03:23:30.779561:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 03:43:30.379602:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 03:43:30.555136:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 03:43:30.679182:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 03:43:30.839708:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 03:43:31.012317:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 03:43:31.173388:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 04:03:30.273634:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 04:03:30.453169:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 04:03:30.632214:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 04:03:31.258063:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 04:03:31.417581:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 04:03:31.565659:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 04:23:29.961489:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 04:23:30.078388:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 04:23:30.234732:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 04:23:30.375563:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 04:23:30.546205:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 04:23:30.678865:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 04:43:29.947144:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 04:43:30.045249:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 04:43:30.225475:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 04:43:30.407532:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 04:43:30.609908:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 04:43:30.836694:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 05:03:29.934322:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 05:03:30.058740:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 05:03:30.184315:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 05:03:30.474472:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 05:03:30.732799:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 05:03:30.966748:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 05:23:29.937671:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 05:23:30.069059:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 05:23:30.177179:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 05:23:30.315926:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 05:23:30.446071:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 05:23:30.704348:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 05:43:29.928598:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 05:43:30.067818:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 05:43:30.163137:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 05:43:30.321266:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 05:43:30.463857:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 05:43:30.911835:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 06:03:29.999584:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 06:03:30.166292:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 06:03:30.278559:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 06:03:30.464973:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 06:03:30.604593:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 06:03:30.803855:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 06:23:29.949900:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 06:23:30.054499:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 06:23:30.172072:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 06:23:30.314842:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 06:23:30.444131:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 06:23:30.609785:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

2025-07-15 18:06:48,822 - INFO - Loaded command: coinflip.py
2025-07-15 18:06:48,825 - INFO - Loaded command: ouroboros.py
2025-07-15 18:06:48,860 - INFO - Loaded command: rpsgame.py
2025-07-15 18:06:48,865 - INFO - Loaded command: rpsvs.py
2025-07-15 18:06:48,868 - INFO - Loaded command: sporty.py
2025-07-15 18:06:48,872 - INFO - Loaded command: update.py
2025-07-15 18:06:48,881 - INFO - Loaded cog: channelmanagement.py
2025-07-15 18:06:48,884 - INFO - Loaded cog: embed.py
2025-07-15 18:06:48,914 - INFO - Loaded cog: finance.py
2025-07-15 18:06:50,325 - INFO - Loaded cog: leaderboard.py
2025-07-15 18:06:50,327 - INFO - Loaded cog: leveling.py
2025-07-15 18:06:50,626 - INFO - Loaded cog: movies.py
2025-07-15 18:06:50,778 - INFO - Loaded cog: notification.py
2025-07-15 18:06:50,786 - INFO - Loaded cog: serverstat.py
2025-07-15 18:06:50,792 - INFO - Loaded cog: tournaments.py
2025-07-15 18:06:50,797 - INFO - Loaded cog: welcome.py
2025-07-15 18:06:50,797 - INFO - Loaded commands and cogs
2025-07-15 18:06:51,235 - INFO - Slash commands synced successfully: 32 commands
2025-07-15 18:06:53,470 - INFO - Ouroboros Is Ready
Exception occurred on 2025-07-15 18:06:53.594810:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

2025-07-15 18:06:53,620 - ERROR - Exception occurred on 2025-07-15 18:06:53.594810:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 18:06:53.758374:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

2025-07-15 18:06:53,760 - ERROR - Exception occurred on 2025-07-15 18:06:53.758374:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 18:06:53.878213:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

2025-07-15 18:06:53,879 - ERROR - Exception occurred on 2025-07-15 18:06:53.878213:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 18:06:54.020670:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

2025-07-15 18:06:54,023 - ERROR - Exception occurred on 2025-07-15 18:06:54.020670:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 18:06:54.167386:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

2025-07-15 18:06:54,169 - ERROR - Exception occurred on 2025-07-15 18:06:54.167386:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 18:06:54.348711:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

2025-07-15 18:06:54,349 - ERROR - Exception occurred on 2025-07-15 18:06:54.348711:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 18:08:38.636486:
'title'
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\movies.py", line 291, in search_saved_media
    title=result["title"],
          ~~~~~~^^^^^^^^^
KeyError: 'title'

2025-07-15 18:08:38,639 - ERROR - Exception occurred on 2025-07-15 18:08:38.636486:
'title'
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\movies.py", line 291, in search_saved_media
    title=result["title"],
          ~~~~~~^^^^^^^^^
KeyError: 'title'

2025-07-15 18:14:59,964 - INFO - Loaded command: coinflip.py
2025-07-15 18:14:59,967 - INFO - Loaded command: ouroboros.py
2025-07-15 18:14:59,982 - INFO - Loaded command: rpsgame.py
2025-07-15 18:14:59,985 - INFO - Loaded command: rpsvs.py
2025-07-15 18:14:59,990 - INFO - Loaded command: sporty.py
2025-07-15 18:14:59,993 - INFO - Loaded command: update.py
2025-07-15 18:15:00,000 - INFO - Loaded cog: channelmanagement.py
2025-07-15 18:15:00,003 - INFO - Loaded cog: embed.py
2025-07-15 18:15:00,031 - INFO - Loaded cog: finance.py
2025-07-15 18:15:01,536 - INFO - Loaded cog: leaderboard.py
2025-07-15 18:15:01,541 - INFO - Loaded cog: leveling.py
2025-07-15 18:15:01,886 - INFO - Loaded cog: movies.py
2025-07-15 18:15:02,058 - INFO - Loaded cog: notification.py
2025-07-15 18:15:02,065 - INFO - Loaded cog: serverstat.py
2025-07-15 18:15:02,073 - INFO - Loaded cog: tournaments.py
2025-07-15 18:15:02,077 - INFO - Loaded cog: welcome.py
2025-07-15 18:15:02,077 - INFO - Loaded commands and cogs
2025-07-15 18:15:02,319 - INFO - Slash commands synced successfully: 32 commands
2025-07-15 18:15:04,620 - INFO - Ouroboros Is Ready
Exception occurred on 2025-07-15 18:15:04.754665:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

2025-07-15 18:15:04,758 - ERROR - Exception occurred on 2025-07-15 18:15:04.754665:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 18:15:04.925008:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

2025-07-15 18:15:04,928 - ERROR - Exception occurred on 2025-07-15 18:15:04.925008:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 18:15:05.223085:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

2025-07-15 18:15:05,224 - ERROR - Exception occurred on 2025-07-15 18:15:05.223085:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 18:15:05.403631:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

2025-07-15 18:15:05,407 - ERROR - Exception occurred on 2025-07-15 18:15:05.403631:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 18:15:05.556956:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

2025-07-15 18:15:05,559 - ERROR - Exception occurred on 2025-07-15 18:15:05.556956:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 18:15:05.735210:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

2025-07-15 18:15:05,737 - ERROR - Exception occurred on 2025-07-15 18:15:05.735210:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

2025-07-15 18:15:21,510 - INFO - Loaded command: coinflip.py
2025-07-15 18:15:21,516 - INFO - Loaded command: ouroboros.py
2025-07-15 18:15:21,533 - INFO - Loaded command: rpsgame.py
2025-07-15 18:15:21,536 - INFO - Loaded command: rpsvs.py
2025-07-15 18:15:21,540 - INFO - Loaded command: sporty.py
2025-07-15 18:15:21,547 - INFO - Loaded command: update.py
2025-07-15 18:15:21,554 - INFO - Loaded cog: channelmanagement.py
2025-07-15 18:15:21,557 - INFO - Loaded cog: embed.py
2025-07-15 18:15:21,584 - INFO - Loaded cog: finance.py
2025-07-15 18:15:23,092 - INFO - Loaded cog: leaderboard.py
2025-07-15 18:15:23,095 - INFO - Loaded cog: leveling.py
2025-07-15 18:15:23,350 - INFO - Loaded cog: movies.py
2025-07-15 18:15:23,508 - INFO - Loaded cog: notification.py
2025-07-15 18:15:23,517 - INFO - Loaded cog: serverstat.py
2025-07-15 18:15:23,525 - INFO - Loaded cog: tournaments.py
2025-07-15 18:15:23,531 - INFO - Loaded cog: welcome.py
2025-07-15 18:15:23,532 - INFO - Loaded commands and cogs
2025-07-15 18:16:02,376 - INFO - Slash commands synced successfully: 32 commands
2025-07-15 18:16:04,836 - INFO - Ouroboros Is Ready
Exception occurred on 2025-07-15 18:16:05.021130:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

2025-07-15 18:16:05,025 - ERROR - Exception occurred on 2025-07-15 18:16:05.021130:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 18:16:05.198283:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

2025-07-15 18:16:05,200 - ERROR - Exception occurred on 2025-07-15 18:16:05.198283:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 18:16:05.310651:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

2025-07-15 18:16:05,312 - ERROR - Exception occurred on 2025-07-15 18:16:05.310651:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 18:16:05.443702:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

2025-07-15 18:16:05,447 - ERROR - Exception occurred on 2025-07-15 18:16:05.443702:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 18:16:05.628765:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

2025-07-15 18:16:05,630 - ERROR - Exception occurred on 2025-07-15 18:16:05.628765:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 18:16:05.786563:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

2025-07-15 18:16:05,788 - ERROR - Exception occurred on 2025-07-15 18:16:05.786563:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 18:36:04.992148:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

2025-07-15 18:36:04,995 - ERROR - Exception occurred on 2025-07-15 18:36:04.992148:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 18:36:05.107336:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

2025-07-15 18:36:05,110 - ERROR - Exception occurred on 2025-07-15 18:36:05.107336:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 18:36:05.275907:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

2025-07-15 18:36:05,276 - ERROR - Exception occurred on 2025-07-15 18:36:05.275907:
403 Forbidden (error code: 50001): Missing Access
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 48, in update_stats
    await channel.delete()
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\abc.py", line 867, in delete
    await self._state.http.delete_channel(self.id, reason=reason)
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

Exception occurred on 2025-07-15 18:36:05.448961:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

2025-07-15 18:36:05,449 - ERROR - Exception occurred on 2025-07-15 18:36:05.448961:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 18:36:05.609488:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

2025-07-15 18:36:05,612 - ERROR - Exception occurred on 2025-07-15 18:36:05.609488:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

Exception occurred on 2025-07-15 18:36:05.839201:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

2025-07-15 18:36:05,840 - ERROR - Exception occurred on 2025-07-15 18:36:05.839201:
403 Forbidden (error code: 50013): Missing Permissions
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\serverstat.py", line 68, in update_stats
    await guild.create_voice_channel(
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\guild.py", line 1471, in create_voice_channel
    data = await self._create_channel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\discord\http.py", line 752, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

2025-07-15 18:52:37,239 - INFO - Loaded command: coinflip.py
2025-07-15 18:52:37,242 - INFO - Loaded command: ouroboros.py
2025-07-15 18:52:37,255 - INFO - Loaded command: rpsgame.py
2025-07-15 18:52:37,258 - INFO - Loaded command: rpsvs.py
2025-07-15 18:52:37,261 - INFO - Loaded command: sporty.py
2025-07-15 18:52:37,264 - INFO - Loaded command: update.py
2025-07-15 18:52:37,272 - INFO - Loaded cog: channelmanagement.py
2025-07-15 18:52:37,275 - INFO - Loaded cog: embed.py
2025-07-15 18:52:37,311 - INFO - Loaded cog: finance.py
2025-07-15 18:52:38,976 - INFO - Loaded cog: leaderboard.py
2025-07-15 18:52:38,980 - INFO - Loaded cog: leveling.py
2025-07-15 18:52:39,334 - INFO - Loaded cog: movies.py
2025-07-15 18:52:39,424 - INFO - Loaded cog: notification.py
2025-07-15 18:52:39,430 - INFO - Loaded cog: serverstat.py
2025-07-15 18:52:39,434 - INFO - Loaded cog: tournaments.py
2025-07-15 18:52:39,436 - INFO - Loaded cog: welcome.py
2025-07-15 18:52:39,438 - INFO - Loaded commands and cogs
2025-07-15 18:52:39,856 - INFO - Slash commands synced successfully: 32 commands
2025-07-15 18:52:42,088 - INFO - Ouroboros Is Ready
Exception occurred on 2025-07-15 18:53:04.970853:
'title'
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\movies.py", line 291, in search_saved_media
KeyError: 'title'

2025-07-15 18:53:04,988 - ERROR - Exception occurred on 2025-07-15 18:53:04.970853:
'title'
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\movies.py", line 291, in search_saved_media
KeyError: 'title'

2025-07-15 18:55:02,237 - INFO - Loaded command: coinflip.py
2025-07-15 18:55:02,241 - INFO - Loaded command: ouroboros.py
2025-07-15 18:55:02,254 - INFO - Loaded command: rpsgame.py
2025-07-15 18:55:02,258 - INFO - Loaded command: rpsvs.py
2025-07-15 18:55:02,261 - INFO - Loaded command: sporty.py
2025-07-15 18:55:02,264 - INFO - Loaded command: update.py
2025-07-15 18:55:02,273 - INFO - Loaded cog: channelmanagement.py
2025-07-15 18:55:02,275 - INFO - Loaded cog: embed.py
2025-07-15 18:55:02,299 - INFO - Loaded cog: finance.py
2025-07-15 18:55:03,483 - INFO - Loaded cog: leaderboard.py
2025-07-15 18:55:03,486 - INFO - Loaded cog: leveling.py
2025-07-15 18:55:03,744 - INFO - Loaded cog: movies.py
2025-07-15 18:55:03,831 - INFO - Loaded cog: notification.py
2025-07-15 18:55:03,835 - INFO - Loaded cog: serverstat.py
2025-07-15 18:55:03,839 - INFO - Loaded cog: tournaments.py
2025-07-15 18:55:03,844 - INFO - Loaded cog: welcome.py
2025-07-15 18:55:03,845 - INFO - Loaded commands and cogs
2025-07-15 18:55:04,096 - INFO - Slash commands synced successfully: 32 commands
2025-07-15 18:55:06,472 - INFO - Ouroboros Is Ready
2025-07-15 19:04:24,198 - INFO - Loaded command: coinflip.py
2025-07-15 19:04:24,202 - INFO - Loaded command: ouroboros.py
2025-07-15 19:04:24,214 - INFO - Loaded command: rpsgame.py
2025-07-15 19:04:24,217 - INFO - Loaded command: rpsvs.py
2025-07-15 19:04:24,219 - INFO - Loaded command: sporty.py
2025-07-15 19:04:24,224 - INFO - Loaded command: update.py
2025-07-15 19:04:24,232 - INFO - Loaded cog: channelmanagement.py
2025-07-15 19:04:24,235 - INFO - Loaded cog: embed.py
2025-07-15 19:04:24,258 - INFO - Loaded cog: finance.py
2025-07-15 19:04:25,369 - INFO - Loaded cog: leaderboard.py
2025-07-15 19:04:25,372 - INFO - Loaded cog: leveling.py
2025-07-15 19:04:25,619 - INFO - Loaded cog: movies.py
2025-07-15 19:04:25,701 - INFO - Loaded cog: notification.py
2025-07-15 19:04:25,705 - INFO - Loaded cog: serverstat.py
2025-07-15 19:04:25,709 - INFO - Loaded cog: tournaments.py
2025-07-15 19:04:25,713 - INFO - Loaded cog: welcome.py
2025-07-15 19:04:25,714 - INFO - Loaded commands and cogs
2025-07-15 19:04:26,052 - INFO - Slash commands synced successfully: 32 commands
2025-07-15 19:04:28,214 - INFO - Ouroboros Is Ready
Exception occurred on 2025-07-15 19:04:40.830703:
list index out of range
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\dbmanager\MoviesManager.py", line 692, in refresh_tmdb_dates
    first_value = await get_media_details("tv", title)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\dbmanager\MoviesManager.py", line 413, in get_media_details
    url = f"{MOVIE_BASE_URL}/{media}/{ids[0]}?api_key={MOVIE_API_KEY}&append_to_response=watch/providers"
                                      ~~~^^^
IndexError: list index out of range

2025-07-15 19:04:40,832 - ERROR - Exception occurred on 2025-07-15 19:04:40.830703:
list index out of range
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\dbmanager\MoviesManager.py", line 692, in refresh_tmdb_dates
    first_value = await get_media_details("tv", title)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\dbmanager\MoviesManager.py", line 413, in get_media_details
    url = f"{MOVIE_BASE_URL}/{media}/{ids[0]}?api_key={MOVIE_API_KEY}&append_to_response=watch/providers"
                                      ~~~^^^
IndexError: list index out of range

2025-07-15 19:09:06,148 - INFO - Loaded command: coinflip.py
2025-07-15 19:09:06,151 - INFO - Loaded command: ouroboros.py
2025-07-15 19:09:06,163 - INFO - Loaded command: rpsgame.py
2025-07-15 19:09:06,167 - INFO - Loaded command: rpsvs.py
2025-07-15 19:09:06,170 - INFO - Loaded command: sporty.py
2025-07-15 19:09:06,173 - INFO - Loaded command: update.py
2025-07-15 19:09:06,179 - INFO - Loaded cog: channelmanagement.py
2025-07-15 19:09:06,182 - INFO - Loaded cog: embed.py
2025-07-15 19:09:06,205 - INFO - Loaded cog: finance.py
2025-07-15 19:09:07,350 - INFO - Loaded cog: leaderboard.py
2025-07-15 19:09:07,353 - INFO - Loaded cog: leveling.py
2025-07-15 19:09:07,595 - INFO - Loaded cog: movies.py
2025-07-15 19:09:07,681 - INFO - Loaded cog: notification.py
2025-07-15 19:09:07,686 - INFO - Loaded cog: serverstat.py
2025-07-15 19:09:07,690 - INFO - Loaded cog: tournaments.py
2025-07-15 19:09:07,694 - INFO - Loaded cog: welcome.py
2025-07-15 19:09:07,694 - INFO - Loaded commands and cogs
2025-07-15 19:09:07,972 - INFO - Slash commands synced successfully: 32 commands
2025-07-15 19:09:10,538 - INFO - Ouroboros Is Ready
Exception occurred on 2025-07-15 19:09:21.770832:
cannot access local variable 'ids' where it is not associated with a value
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\dbmanager\MoviesManager.py", line 692, in refresh_tmdb_dates
    first_value = await get_media_details("tv", title)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\dbmanager\MoviesManager.py", line 407, in get_media_details
    ids = await search_media_id(media, media_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\dbmanager\MoviesManager.py", line 517, in search_media_id
    return ids
           ^^^
UnboundLocalError: cannot access local variable 'ids' where it is not associated with a value

2025-07-15 19:09:21,772 - ERROR - Exception occurred on 2025-07-15 19:09:21.770832:
cannot access local variable 'ids' where it is not associated with a value
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\dbmanager\MoviesManager.py", line 692, in refresh_tmdb_dates
    first_value = await get_media_details("tv", title)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\dbmanager\MoviesManager.py", line 407, in get_media_details
    ids = await search_media_id(media, media_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\dbmanager\MoviesManager.py", line 517, in search_media_id
    return ids
           ^^^
UnboundLocalError: cannot access local variable 'ids' where it is not associated with a value

2025-07-15 19:12:01,986 - INFO - Loaded command: coinflip.py
2025-07-15 19:12:01,988 - INFO - Loaded command: ouroboros.py
2025-07-15 19:12:02,000 - INFO - Loaded command: rpsgame.py
2025-07-15 19:12:02,003 - INFO - Loaded command: rpsvs.py
2025-07-15 19:12:02,007 - INFO - Loaded command: sporty.py
2025-07-15 19:12:02,011 - INFO - Loaded command: update.py
2025-07-15 19:12:02,017 - INFO - Loaded cog: channelmanagement.py
2025-07-15 19:12:02,020 - INFO - Loaded cog: embed.py
2025-07-15 19:12:02,042 - INFO - Loaded cog: finance.py
2025-07-15 19:12:03,144 - INFO - Loaded cog: leaderboard.py
2025-07-15 19:12:03,147 - INFO - Loaded cog: leveling.py
2025-07-15 19:12:03,368 - INFO - Loaded cog: movies.py
2025-07-15 19:12:03,455 - INFO - Loaded cog: notification.py
2025-07-15 19:12:03,460 - INFO - Loaded cog: serverstat.py
2025-07-15 19:12:03,463 - INFO - Loaded cog: tournaments.py
2025-07-15 19:12:03,467 - INFO - Loaded cog: welcome.py
2025-07-15 19:12:03,468 - INFO - Loaded commands and cogs
2025-07-15 19:12:03,689 - INFO - Slash commands synced successfully: 32 commands
2025-07-15 19:12:05,889 - INFO - Ouroboros Is Ready
Exception occurred on 2025-07-15 19:12:17.251641:
cannot access local variable 'id' where it is not associated with a value
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\dbmanager\MoviesManager.py", line 688, in refresh_tmdb_dates
    first_value = await get_media_details("tv", title)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\dbmanager\MoviesManager.py", line 407, in get_media_details
    id = await search_media_id(media, media_name)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\dbmanager\MoviesManager.py", line 515, in search_media_id
    return id
           ^^
UnboundLocalError: cannot access local variable 'id' where it is not associated with a value

2025-07-15 19:12:17,252 - ERROR - Exception occurred on 2025-07-15 19:12:17.251641:
cannot access local variable 'id' where it is not associated with a value
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\dbmanager\MoviesManager.py", line 688, in refresh_tmdb_dates
    first_value = await get_media_details("tv", title)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\dbmanager\MoviesManager.py", line 407, in get_media_details
    id = await search_media_id(media, media_name)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\dbmanager\MoviesManager.py", line 515, in search_media_id
    return id
           ^^
UnboundLocalError: cannot access local variable 'id' where it is not associated with a value

2025-07-15 19:21:32,607 - INFO - Loaded command: coinflip.py
2025-07-15 19:21:32,610 - INFO - Loaded command: ouroboros.py
2025-07-15 19:21:32,623 - INFO - Loaded command: rpsgame.py
2025-07-15 19:21:32,626 - INFO - Loaded command: rpsvs.py
2025-07-15 19:21:32,629 - INFO - Loaded command: sporty.py
2025-07-15 19:21:32,632 - INFO - Loaded command: update.py
2025-07-15 19:21:32,639 - INFO - Loaded cog: channelmanagement.py
2025-07-15 19:21:32,642 - INFO - Loaded cog: embed.py
2025-07-15 19:21:32,665 - INFO - Loaded cog: finance.py
2025-07-15 19:21:33,757 - INFO - Loaded cog: leaderboard.py
2025-07-15 19:21:33,759 - INFO - Loaded cog: leveling.py
2025-07-15 19:21:34,010 - INFO - Loaded cog: movies.py
2025-07-15 19:21:34,095 - INFO - Loaded cog: notification.py
2025-07-15 19:21:34,100 - INFO - Loaded cog: serverstat.py
2025-07-15 19:21:34,104 - INFO - Loaded cog: tournaments.py
2025-07-15 19:21:34,108 - INFO - Loaded cog: welcome.py
2025-07-15 19:21:34,109 - INFO - Loaded commands and cogs
2025-07-15 19:21:34,460 - INFO - Slash commands synced successfully: 32 commands
2025-07-15 19:21:36,701 - INFO - Ouroboros Is Ready
2025-07-15 19:30:57,573 - INFO - Loaded command: coinflip.py
2025-07-15 19:30:57,576 - INFO - Loaded command: ouroboros.py
2025-07-15 19:30:57,589 - INFO - Loaded command: rpsgame.py
2025-07-15 19:30:57,592 - INFO - Loaded command: rpsvs.py
2025-07-15 19:30:57,595 - INFO - Loaded command: sporty.py
2025-07-15 19:30:57,599 - INFO - Loaded command: update.py
2025-07-15 19:30:57,605 - INFO - Loaded cog: channelmanagement.py
2025-07-15 19:30:57,608 - INFO - Loaded cog: embed.py
2025-07-15 19:30:57,631 - INFO - Loaded cog: finance.py
2025-07-15 19:30:58,719 - INFO - Loaded cog: leaderboard.py
2025-07-15 19:30:58,722 - INFO - Loaded cog: leveling.py
2025-07-15 19:30:58,928 - INFO - Loaded cog: movies.py
2025-07-15 19:30:59,011 - INFO - Loaded cog: notification.py
2025-07-15 19:30:59,016 - INFO - Loaded cog: serverstat.py
2025-07-15 19:30:59,020 - INFO - Loaded cog: tournaments.py
2025-07-15 19:30:59,023 - INFO - Loaded cog: welcome.py
2025-07-15 19:30:59,024 - INFO - Loaded commands and cogs
2025-07-15 19:30:59,251 - INFO - Slash commands synced successfully: 32 commands
2025-07-15 19:31:01,542 - INFO - Ouroboros Is Ready
2025-07-15 19:35:07,594 - INFO - Loaded command: coinflip.py
2025-07-15 19:35:07,598 - INFO - Loaded command: ouroboros.py
2025-07-15 19:35:07,615 - INFO - Loaded command: rpsgame.py
2025-07-15 19:35:07,619 - INFO - Loaded command: rpsvs.py
2025-07-15 19:35:07,623 - INFO - Loaded command: sporty.py
2025-07-15 19:35:07,634 - INFO - Loaded command: update.py
2025-07-15 19:35:07,644 - INFO - Loaded cog: channelmanagement.py
2025-07-15 19:35:07,649 - INFO - Loaded cog: embed.py
2025-07-15 19:35:07,674 - INFO - Loaded cog: finance.py
2025-07-15 19:35:08,795 - INFO - Loaded cog: leaderboard.py
2025-07-15 19:35:08,797 - INFO - Loaded cog: leveling.py
2025-07-15 19:35:09,031 - INFO - Loaded cog: movies.py
2025-07-15 19:35:09,116 - INFO - Loaded cog: notification.py
2025-07-15 19:35:09,121 - INFO - Loaded cog: serverstat.py
2025-07-15 19:35:09,124 - INFO - Loaded cog: tournaments.py
2025-07-15 19:35:09,128 - INFO - Loaded cog: welcome.py
2025-07-15 19:35:09,129 - INFO - Loaded commands and cogs
2025-07-15 19:35:09,418 - INFO - Slash commands synced successfully: 32 commands
2025-07-15 19:35:11,794 - INFO - Ouroboros Is Ready
2025-07-15 19:40:04,121 - INFO - Loaded command: coinflip.py
2025-07-15 19:40:04,123 - INFO - Loaded command: ouroboros.py
2025-07-15 19:40:04,135 - INFO - Loaded command: rpsgame.py
2025-07-15 19:40:04,138 - INFO - Loaded command: rpsvs.py
2025-07-15 19:40:04,141 - INFO - Loaded command: sporty.py
2025-07-15 19:40:04,144 - INFO - Loaded command: update.py
2025-07-15 19:40:04,151 - INFO - Loaded cog: channelmanagement.py
2025-07-15 19:40:04,154 - INFO - Loaded cog: embed.py
2025-07-15 19:40:04,175 - INFO - Loaded cog: finance.py
2025-07-15 19:40:05,261 - INFO - Loaded cog: leaderboard.py
2025-07-15 19:40:05,263 - INFO - Loaded cog: leveling.py
2025-07-15 19:40:05,530 - INFO - Loaded cog: movies.py
2025-07-15 19:40:05,614 - INFO - Loaded cog: notification.py
2025-07-15 19:40:05,620 - INFO - Loaded cog: serverstat.py
2025-07-15 19:40:05,625 - INFO - Loaded cog: tournaments.py
2025-07-15 19:40:05,628 - INFO - Loaded cog: welcome.py
2025-07-15 19:40:05,629 - INFO - Loaded commands and cogs
2025-07-15 19:40:06,121 - INFO - Slash commands synced successfully: 32 commands
2025-07-15 19:40:08,420 - INFO - Ouroboros Is Ready
2025-07-15 19:42:48,592 - INFO - Loaded command: coinflip.py
2025-07-15 19:42:48,595 - INFO - Loaded command: ouroboros.py
2025-07-15 19:42:48,608 - INFO - Loaded command: rpsgame.py
2025-07-15 19:42:48,611 - INFO - Loaded command: rpsvs.py
2025-07-15 19:42:48,614 - INFO - Loaded command: sporty.py
2025-07-15 19:42:48,617 - INFO - Loaded command: update.py
2025-07-15 19:42:48,624 - INFO - Loaded cog: channelmanagement.py
2025-07-15 19:42:48,627 - INFO - Loaded cog: embed.py
2025-07-15 19:42:48,652 - INFO - Loaded cog: finance.py
2025-07-15 19:42:49,782 - INFO - Loaded cog: leaderboard.py
2025-07-15 19:42:49,785 - INFO - Loaded cog: leveling.py
2025-07-15 19:42:50,028 - INFO - Loaded cog: movies.py
2025-07-15 19:42:50,130 - INFO - Loaded cog: notification.py
2025-07-15 19:42:50,136 - INFO - Loaded cog: serverstat.py
2025-07-15 19:42:50,140 - INFO - Loaded cog: tournaments.py
2025-07-15 19:42:50,143 - INFO - Loaded cog: welcome.py
2025-07-15 19:42:50,144 - INFO - Loaded commands and cogs
2025-07-15 19:42:50,383 - INFO - Slash commands synced successfully: 32 commands
2025-07-15 19:42:52,624 - INFO - Ouroboros Is Ready
2025-07-15 19:49:57,683 - INFO - Loaded command: coinflip.py
2025-07-15 19:49:57,688 - INFO - Loaded command: ouroboros.py
2025-07-15 19:49:57,710 - INFO - Loaded command: rpsgame.py
2025-07-15 19:49:57,716 - INFO - Loaded command: rpsvs.py
2025-07-15 19:49:57,720 - INFO - Loaded command: sporty.py
2025-07-15 19:49:57,731 - INFO - Loaded command: update.py
2025-07-15 19:49:57,746 - INFO - Loaded cog: channelmanagement.py
2025-07-15 19:49:57,753 - INFO - Loaded cog: embed.py
2025-07-15 19:49:57,792 - INFO - Loaded cog: finance.py
2025-07-15 19:49:59,293 - INFO - Loaded cog: leaderboard.py
2025-07-15 19:49:59,296 - INFO - Loaded cog: leveling.py
2025-07-15 19:49:59,570 - INFO - Loaded cog: movies.py
2025-07-15 19:49:59,663 - INFO - Loaded cog: notification.py
2025-07-15 19:49:59,669 - INFO - Loaded cog: serverstat.py
2025-07-15 19:49:59,673 - INFO - Loaded cog: tournaments.py
2025-07-15 19:49:59,679 - INFO - Loaded cog: welcome.py
2025-07-15 19:49:59,680 - INFO - Loaded commands and cogs
2025-07-15 19:50:00,152 - INFO - Slash commands synced successfully: 32 commands
2025-07-15 19:50:02,623 - INFO - Ouroboros Is Ready
2025-07-15 20:03:32,029 - INFO - Loaded command: coinflip.py
2025-07-15 20:03:32,033 - INFO - Loaded command: ouroboros.py
2025-07-15 20:03:32,055 - INFO - Loaded command: rpsgame.py
2025-07-15 20:03:32,069 - INFO - Loaded command: rpsvs.py
2025-07-15 20:03:32,078 - INFO - Loaded command: sporty.py
2025-07-15 20:03:32,087 - INFO - Loaded command: update.py
2025-07-15 20:03:32,100 - INFO - Loaded cog: channelmanagement.py
2025-07-15 20:03:32,107 - INFO - Loaded cog: embed.py
2025-07-15 20:03:32,170 - INFO - Loaded cog: finance.py
2025-07-15 20:03:33,871 - INFO - Loaded cog: leaderboard.py
2025-07-15 20:03:33,874 - INFO - Loaded cog: leveling.py
2025-07-15 20:03:34,151 - INFO - Loaded cog: movies.py
2025-07-15 20:03:34,237 - INFO - Loaded cog: notification.py
2025-07-15 20:03:34,242 - INFO - Loaded cog: serverstat.py
2025-07-15 20:03:34,246 - INFO - Loaded cog: tournaments.py
2025-07-15 20:03:34,248 - INFO - Loaded cog: welcome.py
2025-07-15 20:03:34,249 - INFO - Loaded commands and cogs
2025-07-15 20:03:34,514 - INFO - Slash commands synced successfully: 32 commands
2025-07-15 20:03:36,809 - INFO - Ouroboros Is Ready
2025-07-15 20:04:55,838 - INFO - Loaded command: coinflip.py
2025-07-15 20:04:55,841 - INFO - Loaded command: ouroboros.py
2025-07-15 20:04:55,854 - INFO - Loaded command: rpsgame.py
2025-07-15 20:04:55,856 - INFO - Loaded command: rpsvs.py
2025-07-15 20:04:55,859 - INFO - Loaded command: sporty.py
2025-07-15 20:04:55,862 - INFO - Loaded command: update.py
2025-07-15 20:04:55,870 - INFO - Loaded cog: channelmanagement.py
2025-07-15 20:04:55,873 - INFO - Loaded cog: embed.py
2025-07-15 20:04:55,895 - INFO - Loaded cog: finance.py
2025-07-15 20:04:57,216 - INFO - Loaded cog: leaderboard.py
2025-07-15 20:04:57,219 - INFO - Loaded cog: leveling.py
2025-07-15 20:04:57,430 - INFO - Loaded cog: movies.py
2025-07-15 20:04:57,514 - INFO - Loaded cog: notification.py
2025-07-15 20:04:57,519 - INFO - Loaded cog: serverstat.py
2025-07-15 20:04:57,523 - INFO - Loaded cog: tournaments.py
2025-07-15 20:04:57,526 - INFO - Loaded cog: welcome.py
2025-07-15 20:04:57,527 - INFO - Loaded commands and cogs
2025-07-15 20:04:57,834 - INFO - Slash commands synced successfully: 32 commands
2025-07-15 20:05:00,045 - INFO - Ouroboros Is Ready
2025-07-15 20:08:00,355 - INFO - Loaded command: coinflip.py
2025-07-15 20:08:00,357 - INFO - Loaded command: ouroboros.py
2025-07-15 20:08:00,369 - INFO - Loaded command: rpsgame.py
2025-07-15 20:08:00,372 - INFO - Loaded command: rpsvs.py
2025-07-15 20:08:00,375 - INFO - Loaded command: sporty.py
2025-07-15 20:08:00,379 - INFO - Loaded command: update.py
2025-07-15 20:08:00,385 - INFO - Loaded cog: channelmanagement.py
2025-07-15 20:08:00,388 - INFO - Loaded cog: embed.py
2025-07-15 20:08:00,410 - INFO - Loaded cog: finance.py
2025-07-15 20:08:01,499 - INFO - Loaded cog: leaderboard.py
2025-07-15 20:08:01,502 - INFO - Loaded cog: leveling.py
2025-07-15 20:08:01,741 - INFO - Loaded cog: movies.py
2025-07-15 20:08:01,825 - INFO - Loaded cog: notification.py
2025-07-15 20:08:01,830 - INFO - Loaded cog: serverstat.py
2025-07-15 20:08:01,834 - INFO - Loaded cog: tournaments.py
2025-07-15 20:08:01,840 - INFO - Loaded cog: welcome.py
2025-07-15 20:08:01,840 - INFO - Loaded commands and cogs
2025-07-15 20:08:02,040 - INFO - Slash commands synced successfully: 32 commands
2025-07-15 20:08:04,242 - INFO - Ouroboros Is Ready
2025-07-15 20:13:31,331 - INFO - Loaded command: coinflip.py
2025-07-15 20:13:31,334 - INFO - Loaded command: ouroboros.py
2025-07-15 20:13:31,347 - INFO - Loaded command: rpsgame.py
2025-07-15 20:13:31,349 - INFO - Loaded command: rpsvs.py
2025-07-15 20:13:31,352 - INFO - Loaded command: sporty.py
2025-07-15 20:13:31,356 - INFO - Loaded command: update.py
2025-07-15 20:13:31,363 - INFO - Loaded cog: channelmanagement.py
2025-07-15 20:13:31,365 - INFO - Loaded cog: embed.py
2025-07-15 20:13:31,388 - INFO - Loaded cog: finance.py
2025-07-15 20:13:32,492 - INFO - Loaded cog: leaderboard.py
2025-07-15 20:13:32,495 - INFO - Loaded cog: leveling.py
2025-07-15 20:13:32,711 - INFO - Loaded cog: movies.py
2025-07-15 20:13:32,797 - INFO - Loaded cog: notification.py
2025-07-15 20:13:32,801 - INFO - Loaded cog: serverstat.py
2025-07-15 20:13:32,805 - INFO - Loaded cog: tournaments.py
2025-07-15 20:13:32,808 - INFO - Loaded cog: welcome.py
2025-07-15 20:13:32,809 - INFO - Loaded commands and cogs
2025-07-15 20:13:33,052 - INFO - Slash commands synced successfully: 33 commands
2025-07-15 20:13:35,296 - INFO - Ouroboros Is Ready
2025-07-15 20:23:34,375 - INFO - Loaded command: coinflip.py
2025-07-15 20:23:34,380 - INFO - Loaded command: ouroboros.py
2025-07-15 20:23:34,399 - INFO - Loaded command: rpsgame.py
2025-07-15 20:23:34,403 - INFO - Loaded command: rpsvs.py
2025-07-15 20:23:34,407 - INFO - Loaded command: sporty.py
2025-07-15 20:23:34,415 - INFO - Loaded command: update.py
2025-07-15 20:23:34,425 - INFO - Loaded cog: channelmanagement.py
2025-07-15 20:23:34,430 - INFO - Loaded cog: embed.py
2025-07-15 20:23:34,458 - INFO - Loaded cog: finance.py
2025-07-15 20:23:36,133 - INFO - Loaded cog: leaderboard.py
2025-07-15 20:23:36,136 - INFO - Loaded cog: leveling.py
2025-07-15 20:23:36,661 - INFO - Loaded cog: movies.py
2025-07-15 20:23:36,790 - INFO - Loaded cog: notification.py
2025-07-15 20:23:36,796 - INFO - Loaded cog: serverstat.py
2025-07-15 20:23:36,804 - INFO - Loaded cog: tournaments.py
2025-07-15 20:23:36,809 - INFO - Loaded cog: welcome.py
2025-07-15 20:23:36,810 - INFO - Loaded commands and cogs
2025-07-15 20:23:37,158 - INFO - Slash commands synced successfully: 33 commands
2025-07-15 20:23:39,390 - INFO - Ouroboros Is Ready
2025-07-15 20:43:15,101 - INFO - Loaded command: coinflip.py
2025-07-15 20:43:15,104 - INFO - Loaded command: ouroboros.py
2025-07-15 20:43:15,118 - INFO - Loaded command: rpsgame.py
2025-07-15 20:43:15,121 - INFO - Loaded command: rpsvs.py
2025-07-15 20:43:15,123 - INFO - Loaded command: sporty.py
2025-07-15 20:43:15,127 - INFO - Loaded command: update.py
2025-07-15 20:43:15,133 - INFO - Loaded cog: channelmanagement.py
2025-07-15 20:43:15,136 - INFO - Loaded cog: embed.py
2025-07-15 20:43:15,159 - INFO - Loaded cog: finance.py
2025-07-15 20:43:16,371 - INFO - Loaded cog: leaderboard.py
2025-07-15 20:43:16,374 - INFO - Loaded cog: leveling.py
2025-07-15 20:43:16,602 - INFO - Loaded cog: movies.py
2025-07-15 20:43:16,691 - INFO - Loaded cog: notification.py
2025-07-15 20:43:16,697 - INFO - Loaded cog: serverstat.py
2025-07-15 20:43:16,701 - INFO - Loaded cog: tournaments.py
2025-07-15 20:43:16,704 - INFO - Loaded cog: welcome.py
2025-07-15 20:43:16,705 - INFO - Loaded commands and cogs
2025-07-15 20:43:16,919 - INFO - Slash commands synced successfully: 33 commands
2025-07-15 20:43:19,205 - INFO - Ouroboros Is Ready
Exception occurred on 2025-07-15 20:43:44.491573:
argument of type 'int' is not iterable
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\movies.py", line 649, in all_media
    embed, discord_file = await pagination_view.get_embed_and_file()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\movies.py", line 345, in get_embed_and_file
    img = self.generate_media_image(page_data)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\movies.py", line 301, in generate_media_image
    date_width = draw.textlength(date_text, font=font)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\PIL\ImageDraw.py", line 809, in textlength
    if self._multiline_check(text):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\PIL\ImageDraw.py", line 558, in _multiline_check
    return split_character in text
           ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'int' is not iterable

2025-07-15 20:43:44,496 - ERROR - Exception occurred on 2025-07-15 20:43:44.491573:
argument of type 'int' is not iterable
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\movies.py", line 649, in all_media
    embed, discord_file = await pagination_view.get_embed_and_file()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\movies.py", line 345, in get_embed_and_file
    img = self.generate_media_image(page_data)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\movies.py", line 301, in generate_media_image
    date_width = draw.textlength(date_text, font=font)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\PIL\ImageDraw.py", line 809, in textlength
    if self._multiline_check(text):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\PIL\ImageDraw.py", line 558, in _multiline_check
    return split_character in text
           ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'int' is not iterable

2025-07-15 20:45:29,143 - INFO - Loaded command: coinflip.py
2025-07-15 20:45:29,147 - INFO - Loaded command: ouroboros.py
2025-07-15 20:45:29,160 - INFO - Loaded command: rpsgame.py
2025-07-15 20:45:29,164 - INFO - Loaded command: rpsvs.py
2025-07-15 20:45:29,166 - INFO - Loaded command: sporty.py
2025-07-15 20:45:29,170 - INFO - Loaded command: update.py
2025-07-15 20:45:29,176 - INFO - Loaded cog: channelmanagement.py
2025-07-15 20:45:29,180 - INFO - Loaded cog: embed.py
2025-07-15 20:45:29,202 - INFO - Loaded cog: finance.py
2025-07-15 20:45:31,120 - INFO - Loaded cog: leaderboard.py
2025-07-15 20:45:31,124 - INFO - Loaded cog: leveling.py
2025-07-15 20:45:31,402 - INFO - Loaded cog: movies.py
2025-07-15 20:45:31,507 - INFO - Loaded cog: notification.py
2025-07-15 20:45:31,513 - INFO - Loaded cog: serverstat.py
2025-07-15 20:45:31,518 - INFO - Loaded cog: tournaments.py
2025-07-15 20:45:31,521 - INFO - Loaded cog: welcome.py
2025-07-15 20:45:31,521 - INFO - Loaded commands and cogs
2025-07-15 20:45:31,856 - INFO - Slash commands synced successfully: 33 commands
2025-07-15 20:45:34,095 - INFO - Ouroboros Is Ready
Exception occurred on 2025-07-15 20:45:39.981927:
argument of type 'int' is not iterable
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\movies.py", line 649, in all_media
    embed, discord_file = await pagination_view.get_embed_and_file()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\movies.py", line 345, in get_embed_and_file
    img = self.generate_media_image(page_data)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\movies.py", line 301, in generate_media_image
    date_width = draw.textlength(date_text, font=font)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\PIL\ImageDraw.py", line 809, in textlength
    if self._multiline_check(text):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\PIL\ImageDraw.py", line 558, in _multiline_check
    return split_character in text
           ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'int' is not iterable

2025-07-15 20:45:39,985 - ERROR - Exception occurred on 2025-07-15 20:45:39.981927:
argument of type 'int' is not iterable
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\movies.py", line 649, in all_media
    embed, discord_file = await pagination_view.get_embed_and_file()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\movies.py", line 345, in get_embed_and_file
    img = self.generate_media_image(page_data)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\movies.py", line 301, in generate_media_image
    date_width = draw.textlength(date_text, font=font)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\PIL\ImageDraw.py", line 809, in textlength
    if self._multiline_check(text):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\PIL\ImageDraw.py", line 558, in _multiline_check
    return split_character in text
           ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'int' is not iterable

2025-07-15 20:49:44,890 - INFO - Loaded command: coinflip.py
2025-07-15 20:49:44,892 - INFO - Loaded command: ouroboros.py
2025-07-15 20:49:44,905 - INFO - Loaded command: rpsgame.py
2025-07-15 20:49:44,908 - INFO - Loaded command: rpsvs.py
2025-07-15 20:49:44,910 - INFO - Loaded command: sporty.py
2025-07-15 20:49:44,914 - INFO - Loaded command: update.py
2025-07-15 20:49:44,920 - INFO - Loaded cog: channelmanagement.py
2025-07-15 20:49:44,923 - INFO - Loaded cog: embed.py
2025-07-15 20:49:44,946 - INFO - Loaded cog: finance.py
2025-07-15 20:49:46,421 - INFO - Loaded cog: leaderboard.py
2025-07-15 20:49:46,423 - INFO - Loaded cog: leveling.py
2025-07-15 20:49:46,672 - INFO - Loaded cog: movies.py
2025-07-15 20:49:46,767 - INFO - Loaded cog: notification.py
2025-07-15 20:49:46,772 - INFO - Loaded cog: serverstat.py
2025-07-15 20:49:46,777 - INFO - Loaded cog: tournaments.py
2025-07-15 20:49:46,782 - INFO - Loaded cog: welcome.py
2025-07-15 20:49:46,783 - INFO - Loaded commands and cogs
2025-07-15 20:49:47,116 - INFO - Slash commands synced successfully: 33 commands
2025-07-15 20:49:49,517 - INFO - Ouroboros Is Ready
Exception occurred on 2025-07-15 20:50:10.928912:
MediaListPaginationView.get_embed_and_file() takes 1 positional argument but 3 were given
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\movies.py", line 650, in all_media
    embed=pagination_view.get_embed_and_file(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MediaListPaginationView.get_embed_and_file() takes 1 positional argument but 3 were given

2025-07-15 20:50:10,933 - ERROR - Exception occurred on 2025-07-15 20:50:10.928912:
MediaListPaginationView.get_embed_and_file() takes 1 positional argument but 3 were given
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\movies.py", line 650, in all_media
    embed=pagination_view.get_embed_and_file(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MediaListPaginationView.get_embed_and_file() takes 1 positional argument but 3 were given

2025-07-15 20:52:19,698 - INFO - Loaded command: coinflip.py
2025-07-15 20:52:19,701 - INFO - Loaded command: ouroboros.py
2025-07-15 20:52:19,713 - INFO - Loaded command: rpsgame.py
2025-07-15 20:52:19,718 - INFO - Loaded command: rpsvs.py
2025-07-15 20:52:19,721 - INFO - Loaded command: sporty.py
2025-07-15 20:52:19,724 - INFO - Loaded command: update.py
2025-07-15 20:52:19,732 - INFO - Loaded cog: channelmanagement.py
2025-07-15 20:52:19,736 - INFO - Loaded cog: embed.py
2025-07-15 20:52:19,759 - INFO - Loaded cog: finance.py
2025-07-15 20:52:20,936 - INFO - Loaded cog: leaderboard.py
2025-07-15 20:52:20,939 - INFO - Loaded cog: leveling.py
2025-07-15 20:52:21,160 - INFO - Loaded cog: movies.py
2025-07-15 20:52:21,502 - INFO - Loaded cog: notification.py
2025-07-15 20:52:21,510 - INFO - Loaded cog: serverstat.py
2025-07-15 20:52:21,519 - INFO - Loaded cog: tournaments.py
2025-07-15 20:52:21,523 - INFO - Loaded cog: welcome.py
2025-07-15 20:52:21,523 - INFO - Loaded commands and cogs
2025-07-15 20:52:21,757 - INFO - Slash commands synced successfully: 33 commands
2025-07-15 20:52:24,174 - INFO - Ouroboros Is Ready
Exception occurred on 2025-07-15 20:52:36.040024:
argument of type 'int' is not iterable
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\movies.py", line 649, in all_media
    embed, file = await pagination_view.get_embed_and_file()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\movies.py", line 345, in get_embed_and_file
    img = self.generate_media_image(page_data)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\movies.py", line 301, in generate_media_image
    date_width = draw.textlength(date_text, font=font)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\PIL\ImageDraw.py", line 809, in textlength
    if self._multiline_check(text):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\PIL\ImageDraw.py", line 558, in _multiline_check
    return split_character in text
           ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'int' is not iterable

2025-07-15 20:52:36,044 - ERROR - Exception occurred on 2025-07-15 20:52:36.040024:
argument of type 'int' is not iterable
Traceback (most recent call last):
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\movies.py", line 649, in all_media
    embed, file = await pagination_view.get_embed_and_file()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\movies.py", line 345, in get_embed_and_file
    img = self.generate_media_image(page_data)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\cogs\movies.py", line 301, in generate_media_image
    date_width = draw.textlength(date_text, font=font)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\PIL\ImageDraw.py", line 809, in textlength
    if self._multiline_check(text):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Inphinithy\Documents\projects\Ourobors-fixed\Pc\Lib\site-packages\PIL\ImageDraw.py", line 558, in _multiline_check
    return split_character in text
           ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'int' is not iterable

2025-07-15 20:54:38,016 - INFO - Loaded command: coinflip.py
2025-07-15 20:54:38,019 - INFO - Loaded command: ouroboros.py
2025-07-15 20:54:38,031 - INFO - Loaded command: rpsgame.py
2025-07-15 20:54:38,037 - INFO - Loaded command: rpsvs.py
2025-07-15 20:54:38,041 - INFO - Loaded command: sporty.py
2025-07-15 20:54:38,045 - INFO - Loaded command: update.py
2025-07-15 20:54:38,052 - INFO - Loaded cog: channelmanagement.py
2025-07-15 20:54:38,055 - INFO - Loaded cog: embed.py
2025-07-15 20:54:38,079 - INFO - Loaded cog: finance.py
2025-07-15 20:54:39,278 - INFO - Loaded cog: leaderboard.py
2025-07-15 20:54:39,281 - INFO - Loaded cog: leveling.py
2025-07-15 20:54:39,521 - INFO - Loaded cog: movies.py
2025-07-15 20:54:39,615 - INFO - Loaded cog: notification.py
2025-07-15 20:54:39,619 - INFO - Loaded cog: serverstat.py
2025-07-15 20:54:39,623 - INFO - Loaded cog: tournaments.py
2025-07-15 20:54:39,627 - INFO - Loaded cog: welcome.py
2025-07-15 20:54:39,627 - INFO - Loaded commands and cogs
2025-07-15 20:54:39,972 - INFO - Slash commands synced successfully: 33 commands
2025-07-15 20:54:42,207 - INFO - Ouroboros Is Ready
